# -*- coding: utf-8 -*-
"""finaL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnAlIP7GPqeG_AvXS712uwWuGxiZNpAF
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""# Params"""


"""# Initializing AI"""

# -*- coding: utf-8 -*-
"""Assignment5_Pig_Tac_Toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_yVipICYYBLyUa_zcRD_iCO9Ttmc1Hp
"""
import jax
import jax.numpy as jnp
from einops import rearrange, reduce, repeat
import matplotlib.pyplot as plt

import numpy as np
import time
import optax
from tqdm import tqdm

#Global constants for size of board
N_ROWS = 4
N_COLS = 4
N_POSSIBLE = N_ROWS*N_COLS #maximum possible number of moves at any stage
P_WIN_ROLLAGAIN = 2.0/3.0 #probability to suceed when you roll again
MAX_GAME_LENGTH = 4*N_ROWS*N_COLS #maximum length a game can go to avoid an infinite game

"""# Rules of Pig-Tac-Toe

## Object of the game
Players place X's and O's on a 4 by 4 grid and try to get 3 of their symbols in a line (either horizontally, vertically, or diagonally). Unlike Tic-Tac-Toe, the game does *not* end when the first 3-in-a-line happens. Instead, the game is played until the board is filled, and any 3-in-a-line is worth 1 victory point. The player with the most victory points at the end of the game wins. A single X or O may contribute to scoring multiple victory points. (For example, having 4 X's in a row effectively counts as 2 victory points). If both players have the same number of victory points at the end of the game, they rejoice in their shared victory.

## How to place Xs and Os
On a turn, a player does the following with their symbol: (Rules described for the X player below, the O player is identical with the symbol changed)

**Step 1.** Place "potential" X: Choose an empty square on the board and place a "potential" X there.

**Step 2.** Decide whether to play it safe and "BANK" or to take a risk and "ROLL":
  - If they choose to "BANK", all the potential X's from this turn become permanent X's on the board. Then the turn is over and it becomes the other players turn.
  - If they choose to "ROLL", they roll a d6.
    - On a dice outcome of 3,4,5,6 they succeed their roll and go back to Step 1 and can place another potential X, and then decide whether to ROLL/BANK again.
    - On a dice outcome of 1 or 2, they fail their roll and they lose all their potential Xs from this turn, which are removed from the board. It then becomes the other player's turn.

## Special Starting Rule
The first player determined randomly (e.g., by a coin flip or die roll). To offset the first player advantage, the player who plays second begins the game with one square chosen at random already filled in.

## Game End Condition
The game ends when all 16 squares are filled, at which point victory points are counted. In the computer implentation, to avoid games going on infinetly long, there is also a maximum game length limit imposed (normally 64 rounds max). If this maximum limit is hit, the game instantly ends and the winner is the player with most victory points at this time.

## Other Project Details

- Project is open ended: make the best possible AI you can by combining course ideas however you want to. Show your work including a recorded mini presentation on what you did.
- Will have a benchmark of some simple AIs to play against on Gradescope.
- For fun only final tournament amongst class members.
- Can work by yourself, or with a partner. Expectations higher if working with partner.
- See CourseLink for details

# Helper Functions for 3 in a line games
"""

def create_k_in_a_lines(k=3):
    '''Creates a (n_k_in_a_lines, N_ROWS, N_COLS) array with all the possible k in a lines. Slow! Try to only run it once...'''
    #Input: k is the length of the k-in-a-rows to generate
    #Output: Boolean array of shape (n_k_in_a_lines, N_ROWS, N_COLS) array with all possible k_in_a_lines

    k_in_a_line_list = []  # List to store winning line_arrays

    # Horizontal lines
    for r in range(N_ROWS):
        for c in range(N_COLS - k + 1):
            line_array = np.zeros((N_ROWS, N_COLS), dtype=bool)
            line_array[r, c:c+k] = True
            k_in_a_line_list.append(line_array)

    # Vertical lines
    for c in range(N_COLS):
        for r in range(N_ROWS - k + 1):
            line_array = np.zeros((N_ROWS, N_COLS), dtype=bool)
            line_array[r:r+k, c] = True
            k_in_a_line_list.append(line_array)

    # Diagonal (bottom-left to top-right)
    for r in range(N_ROWS - k + 1):
        for c in range(N_COLS - k + 1):
            line_array = np.zeros((N_ROWS, N_COLS), dtype=bool)
            for i in range(k):
                line_array[r + i, c + i] = True
            k_in_a_line_list.append(line_array)

    # Diagonal (top-left to bottom-right)
    for r in range(k - 1, N_ROWS):
        for c in range(N_COLS - k + 1):
            line_array = np.zeros((N_ROWS, N_COLS), dtype=bool)
            for i in range(k):
                line_array[r - i, c + i] = True
            k_in_a_line_list.append(line_array)

    # Stack to Final Shape: (n_k_in_a_lines, N_ROWS, N_COLS)
    stacked_k_in_a_lines = np.stack(k_in_a_line_list)
    return stacked_k_in_a_lines

THREE_IN_A_ROW_MASK = jnp.logical_not(create_k_in_a_lines(k=3))
TWO_IN_A_ROW_MASK = jnp.logical_not(create_k_in_a_lines(k=2))
# FOUR_IN_A_ROW_MASK = jnp.logical_not(create_k_in_a_lines(k=4))
#Shape (n_3_in_a_rows, N_ROWS, N_COLS) For a 3x3 board n_3_in_a_rows is 8

@jax.jit
def which_three_in_a_line(board_bool, k=THREE_IN_A_ROW_MASK):
  '''Inputs a boolean board of shape (...,N_ROWS,N_COLS) and outputs a boolean array of shape (...,n_3_in_a_rows) with which of the possible 3-in-a-lines are there'''
  #Input: board_bool shape (..., N_ROWS, N_COLS) representing a subset of a board
  #Output: shape (..., n_3_in_a_lines) of bool with which 3-in-a-lines are there or not

  #Shape (..., 1, N_ROWS, N_COLS) so it can be broadcasted with the create_k_lines_mask
  broadcastable_board = rearrange(board_bool, '... row col -> ... 1 row col')  #Shape (..., 1, N_ROWS, N_COLS) so it can be broadcast

  line_check_board = jnp.logical_or(k, broadcastable_board )
  #Shape: ( ... , n_3_in_a_lines, N_ROW, N_COLS) by broadcasting
  #..By using a logical_or the board will be ALL trues iff there is a 3 in line


  #reduce out the row and column dimensions by doing an 'all' command
  which_lines = reduce(line_check_board , '... n_line r c -> ... n_line', 'all')

  return which_lines

#Examples:
#board = jnp.array([[1,1,1,0],[1,0,0,0],[1,0,0,0],[0,0,0,0]])
#print(which_three_in_a_line(board))

#POSSIBLE_MOVES_ROWCOL is a static array of shape (N_ROWS, N_COLS, N_ROWS, N_COLS) with all possible moves from an *empty* board. The moves are filled in with a single 1, and all empty squaresa re 0.
#The (:,:,row_ix,col_ix) array is what you get when you play in row_ix, col_ix
POSSIBLE_MOVES_ROWCOL = jnp.stack([
    jnp.stack([
        # Set a move (1) at position (row_ix, col_ix)
        jnp.zeros((N_ROWS, N_COLS), dtype=int).at[row_ix, col_ix].set(1)
        for col_ix in range(N_COLS)
    ])
    for row_ix in range(N_ROWS)
])

@jax.jit
def possible_moves(board_int, fill_val):
  '''Inputs a boolean board of shape (...,N_ROWS,N_COLS) and returns a boolean array of shape
   (...,N_POSSIBLE,N_ROWS,N_COLS) with ALL the possible game states after the move
   as well as a an array (...,N_POSSIBLE) of bool with whether or not each move is legal.'''
   #Input: board_int is an int array of shape (...,N_ROWS,N_COLS) which represents the board. Assumes that any "0"s in the board_int is an empty square that can be played in. "fill_val" is the value that is filled in in the empty squares. So some of the 0s get replaced by "fill_vals" in the possible moves.
   #Output: Two arrays: moves, legal
   # moves is shape (...,N_POSSIBLE, N_ROWS, N_COLS) of int with all the possible moves one can makle from board_int. If a move is illegal, it will just return the original board_int.
   # legal is shape (...,N_POSSIBLE) of boolean with whether or not each possible move is a legal move or not. In pig-tac-toe/tic-tac-toe a move is legal if and only the square is empty (i.e. ==0)

  #First we do things with 2 axes, N_ROWS,N_COLS, and then we flatten it down to a single axis of N_POSSIBLE = N_ROWS*N_COLS

  legal_moves_ROWCOL = (board_int == 0) #Shape (..., N_ROWS, N_COLS)
  #Create a shape (..., N_ROWS, N_COLS, 1, 1) so it can be broadcast correctly
  broadcastable_legal = rearrange(legal_moves_ROWCOL, '... row col -> ... row col 1 1')

  #add axes to the board so it can be broadcast
  broadcastable_board = rearrange(board_int, '... row col -> ... row col 1 1')

  #Play the legal moves by adding the move to it. Otherwise return the original board.
  broadcastable_fill_val = rearrange(fill_val, '... -> ... 1 1 1 1')

  #Create the moves played in the legal moves, using the POSSIBLE_MOVES_ROWCOL array.
  move_played_ROWCOL = jnp.where(broadcastable_legal,
                                 broadcastable_board + broadcastable_fill_val*POSSIBLE_MOVES_ROWCOL, broadcastable_board)

  #flatten it the down to the promised axis.
  move_played_flat = rearrange(move_played_ROWCOL, '... row_game col_game row_move col_move -> ... (row_move col_move) row_game col_game')

  legal_moves_flat = rearrange(legal_moves_ROWCOL, '... row_move col_move  -> ... (row_move col_move)')

  return move_played_flat, legal_moves_flat

@jax.jit
def P1_P2_swap(board):
  #Swaps the 1s <-> 2s, and -1s <-> -2s  so that the AI can always assume that its Player 1
  swap_neg = jnp.where(board == -1, -2, jnp.where(board == -2, -1, board))
  swap_pos = jnp.where(swap_neg == 1, 2, jnp.where(swap_neg == 2, 1, swap_neg))
  return swap_pos

@jax.jit
def select_moves_by_ix(moves, ixs):
  '''Given the choices in ixs, pull the correct move out of the moves array'''
  #INPUT: moves is shape (...,N_POSSIBLE, N_ROWS,N_COLS) with the possible moves
  #       ix is shape (...) with the ixs that were chosen
  #OUTPUT: (...,N_ROWS,N_COLS) with the chosen move. Similar to moves[ixs] but works even for higher dimension sizes.

  #add dimensions so it can be broadcast against the moves
  broadcastable_ixs = rearrange(ixs, '... -> ... 1 1 1')

  # Use take_along_axis to select the corresponding moves along the N_POSSIBLE axis (-3), which is the "N_POSSIBLE" axis.
  selected_moves = jnp.take_along_axis(moves, broadcastable_ixs, axis=-3)

  # since moves has shape (..., N_POSSIBLE, N_ROW, N_COL) so after selection we get (..., 1, N_ROW, N_COL)

  # Remove the singleton dimension
  selected_moves = rearrange(selected_moves, '... 1 row col -> ... row col')
  return selected_moves

"""# The Random Move AI"""

def random_move_AI(key, moves, legal, board):
  '''Simplest possible AI that returns a random legal move and chooses to roll again or not purely at random'''
  #Input: key is a JAX random key object
  #  moves is shape (N_POSSIBLE, N_ROW, N_COL) with the possible moves
  #  legal is shape (N_POSSIBLE) with whether or not each move is possible
  #  board is shape (N_ROW, N_COL) with the current board (i.e. the situation *before* this turn)

  #Output: move_ix, roll_again
  #move_ix is an ix for a *legal* move
  #roll_again is whether or not to roll again

  #Note: The AI always plays as if its Player 1. The board state is swapped in the implentation before it is sent to the AI to make sure this is the case!

  #Random keys used for randomness
  key, subkey_1, subkey_2 = jax.random.split(key, 3)

  #Choose a random move, but only amongst the legal moves
  move_ix = jax.random.choice(subkey_1, a=N_POSSIBLE, p=legal)
  #"p=legal" means that the probability of choosing an illegal move is 0.

  #Choose to roll again or not.
  #roll_again = 1 means to roll again, and roll_again = 0 mean to not!
  roll_again = jax.random.choice(subkey_2, np.arange(2,dtype=int))

  return move_ix, roll_again

"""# My AI"""

### --- NEURAL NETWORK STUFF ---
input_size = 196 # determined by number of features + one hot inputs
hidden_size = 64
output_size = 1 #one number for the output!
q_output_size = 2


def init_params(key, input_size, hidden_size, output_size):
    """Initialize network parameters (weights and biases)"""
    # Weights and biases for the first layer (input to hidden)
    key, subkey = jax.random.split(key)
    W1 = jax.random.normal(subkey, (input_size, hidden_size)) * 0.1
    b1 = jnp.zeros(hidden_size)

    # Weights and biases for the second layer (hidden to output)
    key, subkey = jax.random.split(key)
    W2 = jax.random.normal(subkey, (hidden_size, hidden_size)) * 0.1
    b2 = jnp.zeros(hidden_size)

    # Weights and biases for the second layer (hidden to output)
    key, subkey = jax.random.split(key)
    W3 = jax.random.normal(subkey, (hidden_size, output_size)) * 0.1
    b3 = jnp.zeros(output_size)

    return (W1, b1, W2, b2, W3, b3)

@jax.jit
def value(params, board):
    W1, b1, W2, b2, W3, b3 = params
    one_hot_neg1 = (board == -1)  # Where board is -1
    one_hot_0 = (board == 0)     # Where board is 0
    one_hot_1 = (board == 1)     # Where board is 1
    one_hot_2 = (board == 2)      # Where board is 2
                                
    # Stack along a new axis to form a one-hot encoding (last dimension will be 4)
    one_hot = jnp.stack([one_hot_neg1, one_hot_1, one_hot_0, one_hot_2], axis=-1)  # Shape (..., N_ROWS, N_COLS, 4)

    # Calculate potential three-in-a-lines and two-in-a-lines for each player
    p1_potential = jnp.logical_or((board==1), (board==0))
    p1_potential_VP = which_three_in_a_line(p1_potential)
    p1_potential_twos = which_three_in_a_line(p1_potential, TWO_IN_A_ROW_MASK)

    p2_potential = jnp.logical_or((board==2), (board==0))
    p2_potential_VP = which_three_in_a_line(p2_potential)
    p2_potential_twos = which_three_in_a_line(p2_potential, TWO_IN_A_ROW_MASK)

    # Flatten the last three dimensions into a single vector using einops
    flat_one_hot = rearrange(one_hot, "... N_ROWS N_COLS C -> ... (N_ROWS N_COLS C)")

    # Create input vector x
    x = jnp.concatenate([flat_one_hot, p1_potential_VP, p1_potential_twos, p2_potential_VP, p2_potential_twos], axis=-1)

    first = jnp.dot(x, W1) + b1
    hidden1 = jnp.dot(jax.nn.relu(first), W2) + b2
    output = 2.0*jax.nn.sigmoid(jnp.dot(jax.nn.relu(hidden1), W3) + b3) - 1.0
    clean_output = rearrange(output, "... 1 -> ...")
    return clean_output

@jax.jit
def roll_again_value(params, board):
  W1, b1, W2, b2, W3, b3 = params
  one_hot_neg1 = (board == -1)  # Where board is -1
  one_hot_0 = (board == 0)     # Where board is 0
  one_hot_1 = (board == 1)     # Where board is 1
  one_hot_2 = (board == 2)      # Where board is 2

  # Stack along a new axis to form a one-hot encoding (last dimension will be 4)
  one_hot = jnp.stack([one_hot_neg1, one_hot_1, one_hot_0, one_hot_2], axis=-1)  # Shape (..., N_ROWS, N_COLS, 4)

  # Calculate potential three-in-a-lines and two-in-a-lines for each player
  p1_potential = jnp.logical_or((board==1), (board==0))
  p1_potential_VP = which_three_in_a_line(p1_potential)
  p1_potential_twos = which_three_in_a_line(p1_potential, TWO_IN_A_ROW_MASK)

  p2_potential = jnp.logical_or((board==2), (board==0))
  p2_potential_VP = which_three_in_a_line(p2_potential)
  p2_potential_twos = which_three_in_a_line(p2_potential, TWO_IN_A_ROW_MASK)

  # Flatten the last three dimensions into a single vector using einops
  flat_one_hot = rearrange(one_hot, "... N_ROWS N_COLS C -> ... (N_ROWS N_COLS C)")

  # Create input vector x
  x = jnp.concatenate([flat_one_hot, p1_potential_VP, p1_potential_twos, p2_potential_VP, p2_potential_twos], axis=-1)

  first = jnp.dot(x, W1) + b1
  hidden1 = jnp.dot(jax.nn.relu(first), W2) + b2
  output = 2.0*jax.nn.sigmoid(jnp.dot(jax.nn.relu(hidden1), W3) + b3) - 1.0
  return output

key = jax.random.PRNGKey(42)
params = init_params(key, input_size, hidden_size, output_size)
q_params = init_params(key, input_size, hidden_size, q_output_size)

optimizer = optax.adam(learning_rate=1e-3) #rate between 1e-2 and 1e-3 is a good choice!
optimizer_state = optimizer.init(params)

q_optimizer = optax.adam(learning_rate=1e-3) #rate between 1e-2 and 1e-3 is a good choice!
q_optimizer_state = q_optimizer.init(q_params)

# output is value of rolling again and value of stopping
# training data will just be value of rolling again

def loss(params,board, actual, which_ones):
  vals = value(params, board);
  squared_error = (vals - actual)**2
  masked_losses = squared_error * which_ones
  return jnp.sum(masked_losses) / jnp.sum(which_ones)

def action_loss(params, board, actual, actions, which_ones):
  q_vals = roll_again_value(params, board)

  # create a one hot mask that selects one of the actions [stop, roll_again]
  mask = jax.nn.one_hot(actions, num_classes=2)

  # calculate the loss by selecting the result of q vals and comparing it to the actual value
  chosen_q_val = jnp.sum(q_vals * mask, axis=-1)
  squared_error = (chosen_q_val - actual)**2
  masked_losses = squared_error * which_ones
  return jnp.sum(masked_losses) / jnp.sum(which_ones)

# loss_grads
loss_grad = jax.grad(loss)
q_loss_grad = jax.grad(action_loss)


def my_AI(params, q_params, key, moves, legal, board):
  #Input: key is a JAX random key object
  #  moves is shape (N_POSSIBLE, N_ROW, N_COL) with the possible moves
  #  legal is shape (N_POSSIBLE) with whether or not each move is possible
  #  board is shape (N_ROW, N_COL) with the current board (i.e. the situation *before* this turn)

  # Get values
  vals = value(params, moves)

  # Remove illegal moves
  vals = jnp.where(legal, vals, -jnp.inf)

  # Get move index
  move_ix = jnp.argmax(vals)

  # Get roll again values
  roll_again_vals = roll_again_value(q_params, board)

  # Get what action to take (stop, roll_again)
  action_ix = jnp.argmax(roll_again_vals)

  return move_ix, action_ix

#Function to print out a board state as text
def print_board(board):
    symbols = {-2:"o", -1:"x", 0:".",1:'X', 2:'O'} #what each board entry represents
    # 1 = Player 1 actual piece (X)
    # -1 = Player 1 potential piece (x)
    # 2 = Player 2 actual piece (O)
    # -2 = Player 2 potential piece (o)

    for row in range(N_ROWS):
        print(" | ".join(symbols[int(board[row,col])] for col in range(N_COLS)))
        print("-"*(N_COLS*4-3))
    print()

#########
# PIG TAC TOE Game loop
# Simulates ONE game a time
#########

# Set the for params to the initial params
foe_params = params
foe_q_params = q_params

num_episodes = 1000 #number of episodes to simulate
num_games = 100 # minimum number of games to run
VERBOSE = False # whether or not to print game details as you go.

AIs = [my_AI, my_AI] #AIs for Player 1 and Player 2 are both my AI
key = jax.random.PRNGKey(int(time.time())) #random key used for JAX

# keeping track of losses and total reward for plotting
losses = []
total_rewards = []

for episode in tqdm(range(num_episodes)):
  
  # keep track of the avg loss over 50 games
  episode_avg_loss = 3

  # keep track of the number of games completed
  games = 0

  # keep track of the last 50 losses
  recent_losses = []

  print(f"\n====Episode {episode+1}====") if VERBOSE else None
  # Run each episode for at least 100 games, and then until average loss across 50 games is less than 0.10
  while episode_avg_loss > 0.10 or games < num_games:

    games+= 1

    print(f"\n====Episode {episode+1}====") if VERBOSE else None

    ##############
    #Initialize things for the game
    ##############
    key, subkey = jax.random.split(key)
    current_player = ( jax.random.uniform(subkey)<0.5 ) + 1 #choose random starting player
    board = jnp.zeros((N_ROWS, N_COLS), dtype=int) #board starts out empty
    game_over = False
    key, subkey_ai, subkey_roll = jax.random.split(key,3) #random keys to give to the ai and to give to the rolls
    ai_key = jax.random.split(subkey_ai, MAX_GAME_LENGTH)
    roll_key = jax.random.split(subkey_roll, MAX_GAME_LENGTH)

    #Special Starting Rule: non-starting player gets a random starting piece!
    opposite_player = 3 - current_player
    moves, legal  = possible_moves(board, fill_val = opposite_player)
    key, subkey = jax.random.split(key)
    random_move_ix, _ = random_move_AI(subkey, moves, legal, board)
    board = select_moves_by_ix(moves, random_move_ix) #board now contains a random move for the opposite player
    print("Starting Board: ") if VERBOSE else None
    print_board(board) if VERBOSE else None

    # Setting up the history containers for training the neural networks
    moves_history = jnp.zeros((MAX_GAME_LENGTH * 4, N_ROWS, N_COLS))
    flipped_moves_history = jnp.zeros((MAX_GAME_LENGTH * 4, N_ROWS, N_COLS))
    player_history = jnp.zeros((MAX_GAME_LENGTH * 4,))
    action_history = jnp.zeros((MAX_GAME_LENGTH * 4,))

    ############
    # Main Loop for the Truns
    ############
    for turn in range(MAX_GAME_LENGTH):
      if game_over == False:
        #######
        #STEP 1: Play a potential piece
        #######
        #
        # The potential piece is added as a negative value!
        # So -1 represents a potential player 1 piece, and -2 is a potential player 2 piece.

        moves, legal = possible_moves(board, fill_val=-current_player) #Get all possible moves and their legality

        if current_player == 1:
          move_ix, roll_again = AIs[0](params, q_params, ai_key[turn], moves, legal, board)
        elif current_player == 2:
            # the foe (player 2) will play as the random ai once every 100 games
          if games % 100 == 0:
            move_ix, roll_again = random_move_AI(ai_key[turn], moves, legal, P1_P2_swap(board))
          else:
            #If its player 2's turn we swap P1 <-> P2 so that the AI can think from P1's point of view
            move_ix, roll_again = AIs[1](foe_params, foe_q_params, ai_key[turn], P1_P2_swap(moves), legal, P1_P2_swap(board))

        
        #AI chooses a move_ix from the available moves
        board = select_moves_by_ix(moves, move_ix) #Update the board

        if current_player == 1:
          temp_board = board
          temp_board_mirror = jnp.flip(temp_board, axis=1)

          # When its my ai's turn, generate all permutations of the board and save them
          for i in range(4):
            moves_history = moves_history.at[turn * 4 + i].set(
              temp_board
            )
            flipped_moves_history = moves_history.at[turn * 4 + i].set(
              temp_board_mirror
            )
            temp_board = jnp.rot90(temp_board)
            temp_board_mirror = jnp.flip(temp_board, axis=1)

            # This ensures player history is the same size
            player_history = player_history.at[turn * 4 + i].set(current_player)

        print(f"Turn #{turn}") if VERBOSE else None
        print_board(board) if VERBOSE else None

        #########
        #STEP 2: Choose to roll again or stop
        #########
        if roll_again: #if the AI chose to roll again...
          print("  Chose to roll again!") if VERBOSE else None

          # Ensure to update action history, it must match the size of the other historys
          for i in range(4):
              action_history = action_history.at[turn * 4 + i].set(1)

          #Did it suceed?
          roll_outcome = (jax.random.uniform(roll_key[turn]) < P_WIN_ROLLAGAIN)
          if roll_outcome == 0:
            print("  ..and failed!") if VERBOSE else None
            board = jnp.where(board < 0, 0, board) #delete potential pieces
            current_player = 3 - current_player #change player
          else:
            print("  ..and suceeded!") if VERBOSE else None
            pass #if you win the roll just keep going!

        elif roll_again == 0:
          print("  Chose to stop!") if VERBOSE else None
          board = jnp.abs(board) #potential pieces become real!
          current_player = 3 - current_player #change player

        #check if game is over by counting the number of empty squares
        empty_squares = reduce(board == 0, '... row col -> ...', 'sum')
        game_over = (empty_squares == 0)


    ####
    # After game clean up
    ####
    board = jnp.abs(board) #make any potential pieces real, this is needed if the game ends with the player choosing to roll again even if the board is full or if game ends at the max-length limit
    print(f"Game End") if VERBOSE else None
    print_board(board) if VERBOSE else None

    #count up victory points, +1 for Player 1 and -1 for Player 2
    #multuply by 1 to conver the bool to int
    which_victory_points = 1*which_three_in_a_line(board == 1) - 1*which_three_in_a_line(board == 2)
    net_victory_points = reduce(which_victory_points, '... n_line -> ...', 'sum')
    game_winner_reward = jnp.sign(net_victory_points)

    # Update params with regular game boards
    grads = loss_grad(params, moves_history, game_winner_reward, player_history)
    updates, optimizer_state = optimizer.update(grads, optimizer_state)
    params =  optax.apply_updates(params, updates)

    # Update params with flipped game boards
    grads = loss_grad(params, moves_history, game_winner_reward, player_history)
    updates, optimizer_state = optimizer.update(grads, optimizer_state)
    params =  optax.apply_updates(params, updates)

    # Update params with regular game boards
    q_grads = q_loss_grad(q_params, moves_history, game_winner_reward, action_history, player_history)
    q_updates, q_optimizer_state = q_optimizer.update(q_grads, q_optimizer_state)
    q_params = optax.apply_updates(q_params, q_updates)

    # Update params with regular game boards
    q_grads = q_loss_grad(q_params, flipped_moves_history, game_winner_reward, action_history, player_history)
    q_updates, q_optimizer_state = q_optimizer.update(q_grads, q_optimizer_state)
    q_params = optax.apply_updates(q_params, q_updates)

    # Apply the non-zero mask to filter out all-zero boards
    avg_loss = loss(params, moves_history, game_winner_reward, player_history)
    # losses.append(float(avg_loss)) for plotting

    recent_losses.append(avg_loss)

    if len(recent_losses) > 50:
      recent_losses.pop(0)

    if recent_losses:
      episode_avg_loss = jnp.mean(jnp.array(recent_losses))

  foe_params = params
  foe_q_params = q_params